# Copyright (c) 2025 Salvo Giangreco
# SPDX-License-Identifier: GPL-3.0-or-later

# SEC Floating Feature configuration file for Samsung Exynos 9825 devices (exynos9825)

# SPen
SEC_FLOATING_FEATURE_FRAMEWORK_CONFIG_SPEN_GARAGE_SPEC=type=insert, bundled=true
SEC_FLOATING_FEATURE_FRAMEWORK_CONFIG_SPEN_VERSION=70

# Enable 360 Lite Portrait
SEC_FLOATING_FEATURE_GALLERY_CONFIG_LIVEFOCUS_EFFECT_DUAL_BOKEH=BLUR,EFFECT,BIGBOKEH,PORTRAIT,RELIGHT,REFOCUS,LIGHT360,PL_LITE_360
